import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		   
		String children = "";
		double totalSum = 0;
		int two = 0;
		int three = 0;
		int four = 0;
		String mostCommon = "";
		for(int i = 0; i < T; i++){
			int sumTemp = 0;
			while((children.indexOf('g') == -1) || (children.indexOf('b') == -1)){
				if(generator.nextDouble() < 0.5){
					children = children + "g ";
				} else {
					children = children + "b ";
				}
				sumTemp++;
				totalSum++;
			}
			if(sumTemp == 2){
				two++;
				if(two > three && two > four){
					mostCommon = "The most common number of children is 2.";
				}
			} 
			if(sumTemp == 3){
				three++;
				if(three > two && three > four){
					mostCommon = "The most common number of children is 3.";
				}
			} 
			if(sumTemp >= 4){
				four++;
				if(four > three && four > two){
					mostCommon = "The most common number of children is 4 or more.";
				}
			}
			sumTemp = 0;
			children = "";
		}
		double average = (totalSum / T);
		System.out.println("Average: " + average + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + two);
		System.out.println("Number of families with 3 children: " + three);
		System.out.println("Number of families with 4 or more children: " + four);
		System.out.println(mostCommon);
	}
	
}
